name: Jekyll Deployment

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: only keep what we need
      run: rm -rv $GITHUB_WORKSPACE/ansible-labs-summit2020/ansible-tower-getting-started

    # Standard usage
    - uses:  helaili/jekyll-action@2.0.0
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
